<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    
    <title>Let's Do IT - серьзеный сделки</title>
    
    <meta name="description" content="Упрощенная система заказов">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, max-scale=1.0">
    
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
    <!--[if lte IE 8]>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/grids-responsive-old-ie-min.css">
    <link rel="stylesheet" href="/css/layouts/blog-old-ie.css">
    <![endif]-->
    <!--[if gt IE 8]><!-->
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/grids-responsive-min.css">
    <link rel="stylesheet" href="/css/layouts/blog.css">

</head>
<body>
    <div id="layout" class="pure-g">
        <div class="sidebar pure-u-1 pure-u-md-1-4">
            <div class="header">
                <h1 class="brand-title"><a href="/">Let's Do IT</a></h1>
                <h2 class="brand-tagline">Система управления вашими заказами</h2>

                <nav class="nav">
                    <ul class="nav-list">
                        <? if(!_v('is_auth')): ?>
                            <li class="nav-item">
                                <a class="pure-button" href="/auth/auth">Войти</a>
                            </li>
                            <li class="nav-item">
                                <a class="pure-button" href="/auth/register">Присоедениться</a>
                            </li>
                        <? else : ?>
                            <li class="nav-item">
                                <a class="pure-button" href="/order/list">Доступные заказы</a>
                            </li>
                            <li class="nav-item">
                                <a class="pure-button" href="/order/mine">Мои заказы</a>
                            </li>
                            <li class="nav-item">
                                <a class="pure-button" href="/order/create">Добавить заказ</a>
                            </li>
                            <li class="nav-item">
                                <a class="pure-button" href="/user/profile">Профиль</a>
                            </li>
                            <li class="nav-item">
                                <a class="pure-button" href="/billing/add">Пополнить счет</a>
                            </li>
                        <? endif; ?>
                    </ul>
                </nav>
            </div>
        </div>
        <div class="content pure-u-1 pure-u-md-3-4">
            <?=$content?>
            <? if(core_has_log()): ?>
                <div style="font-size: 83%">
                    <h2>System Logs</h2>
                    <? foreach (core_get_log() as $str): ?>
                        <div><?=$str?></div> 
                    <? endforeach; ?>
                </div>
            <? endif; ?>
        </div>
    </div>
</body>
</html>