<div class="pure-u-1"><?=_v('msg', '') ?></div>
<div class="pure-u-1">
    <h1>Войдите</h1>
    <form class="pure-form pure-form-aligned" method="post">
        <fieldset>
            <div class="pure-control-group">
                <label for="email">Email Address</label>
                <input id="email" name="email" type="email" placeholder="Email Address">
            </div>
            
            <div class="pure-control-group">
                <label for="password">Password</label>
                <input id="password" type="password" name="pass" placeholder="Password">
            </div>
            <div class="pure-controls">
                <button type="submit" class="pure-button pure-button-primary">Submit</button>
            </div>
        </fieldset>
    </form>
</div>