<div class="pure-u-1"><?=_v('msg') ?></div>
    
<div class="pure-u-1">
    <h1>Для регистрации заполните форму</h1>
    <form class="pure-form pure-form-aligned" method="post" action="">
        <fieldset>
            <div class="pure-control-group">
                <label for="name">Username</label>
                <input id="name" name="name" type="text" placeholder="Username">
            </div>
            
            <div class="pure-control-group">
                <label for="password">Password</label>
                <input id="password" name="pass" type="password" placeholder="Password">
            </div>
            
            <div class="pure-control-group">
                <label for="email">Email Address</label>
                <input id="email" name="email" type="email" placeholder="Email Address">
            </div>
            <div class="pure-controls">
<!--                <label for="cb" class="pure-checkbox">-->
<!--                    <input id="cb" type="checkbox"> I've read the terms and conditions-->
<!--                </label>-->
                
                <button type="submit" class="pure-button pure-button-primary">Submit</button>
            </div>
        </fieldset>
    </form>
</div>