<div class="content pure-u-1 pure-u-md-3-4">
    <div>
        <!-- A wrapper for all the blog posts -->
        <div class="posts">
            <h1 class="content-subhead">intro</h1>

            <!-- A single blog post -->
            <section class="post">
                <header class="post-header">
                    <h2 class="post-title">Добро пожаловать!</h2>
                </header>

                <div class="post-description">
                    <p>
                        На нашем проекте вы можете размещать ваши заказы любого свойства, а мы позаботимся о том
                        чтобы они нашли своего испольнителя. <br>
                        Чтобы разместить свой первый заказ пожаулйста
                        <a href="/auth/register">пройдите простой процесс регистрации</a> <br>
                        Если вы уже с нами -  <a href="/auth/auth">войдите в личный кабинет</a>
                    </p>
                </div>
            </section>
        </div>
    </div>
</div>