<style type="text/css">
    input {
        width: 100%;
    }
</style>

<div class="pure-u-1"><?= _v('msg', '') ?></div>
<div class="pure-u-1">
    <h1>Добавление заказа</h1>
    
    <form class="pure-form pure-form-stacked" method="post">
        <fieldset>
            
            <div class="pure-g">
                
                <div class="pure-u-1 pure-u-md-2-3">
                    <label for="order_title">Короткое описание</label>
                    <input id="order_title" name="title" type="text" placeholder="Короткое описание">
                </div>
                
                <div class="pure-u-1 pure-u-md-2-3">
                    <label for="order_title">Цена за выполнение</label>
                    <input id="order_title" name="cost" type="number" placeholder="Цена">
                </div>
                
                <div class="pure-u-1 pure-u-md-2-3">
                    <label for="order_desc">Полное описание</label>
                    <textarea id="order_desc" type="text" name="desc" placeholder="Детально опишите что нужно делать"
                              style="width: 100%" rows="10"></textarea>
                </div>
                
                <div class="pure-u-1">
                    <button type="submit" class="pure-button pure-button-primary">Сохранить</button>
                </div>
        </fieldset>
    </form>
</div>